### ISSUE TITLE
DNS resultion / nslookup fails with :latest (uClibc)

### ISSUE THREAD

**Issue by m-kraus** [prometheus/busybox#18]
I ran into this issue while modelling a demo setup using docker-compose and multiple networks: newer Thanos images as well as Prometheus images starting from 2.4.3 based upon this image were not able to resolve addresses in docker-compose.

Digging down the error i found out that using Prometheus image 2.4.2 nslookup was still working, whereas with 2.4.3 and onwards it seemed broken.

I then compared the uclib and glibc version of this image and found out, that it still works with the glibc version.

Here's a ```docker-compose.yml``` file to reproduce:
```
version: "3.5"

networks:
  whole:

services:
  hostone:
    image: quay.io/prometheus/busybox:latest
    ports: []
    networks:
      - whole
    volumes: []
    environment: []
    entrypoint: sh
    command:
    - -c
    - while sleep 2 ; do nslookup hosttwo ; echo ----- ; done
  hosttwo:
    image: quay.io/prometheus/busybox:glibc
    ports: []
    networks:
      - whole
    volumes: []
    environment: []
    entrypoint: sh
    command:
    - -c
    - while sleep 2 ; do nslookup hostone ; echo ----- ; done
```

This is the output:
```
...
issue_dns_hostone_1 | Server:		127.0.0.11
issue_dns_hostone_1 | Address:	127.0.0.11:53
issue_dns_hostone_1 |
issue_dns_hostone_1 | Non-authoritative answer:
issue_dns_hostone_1 |
issue_dns_hostone_1 | *** Can't find hosttwo: No answer
issue_dns_hostone_1 |
issue_dns_hostone_1 | -----
issue_dns_hosttwo_1 | Server:		127.0.0.11
issue_dns_hosttwo_1 | Address:	127.0.0.11:53
issue_dns_hosttwo_1 |
issue_dns_hosttwo_1 | Non-authoritative answer:
issue_dns_hosttwo_1 |
issue_dns_hosttwo_1 | Non-authoritative answer:
issue_dns_hosttwo_1 | Name:	hostone
issue_dns_hosttwo_1 | Address: 172.29.0.3
issue_dns_hosttwo_1 |
issue_dns_hosttwo_1 | -----
...
```

Maybe the commits 52dbfa4 and 0134a71 are releated to this issue - the fact that Prometheus 2.4.2 still works and 2.4.3 not could correlate to this by time.

Thank you and best regards,
Michael

**Comment by SuperQ** [comment]
It could be related to the new nsswitch.conf. I wonder if uClibc doesn't like the file.

**Comment by m-kraus** [comment]
I rebuilt a docker image locally omitting /etc/nsswitch.conf - nslookup still fails:

```
...
issue_dns_hostthree_1 | Server:		127.0.0.11
issue_dns_hostthree_1 | Address:	127.0.0.11:53
issue_dns_hostthree_1 |
issue_dns_hostthree_1 | Non-authoritative answer:
issue_dns_hostthree_1 |
issue_dns_hostthree_1 | *** Can't find hostone: No answer
issue_dns_hostthree_1 |
issue_dns_hostthree_1 | -----
...
```

It's even failing with ``` busybox:uclibc```

```
...
issue_dns_hostfour_1 | Server:		127.0.0.11
issue_dns_hostfour_1 | Address:	127.0.0.11:53
issue_dns_hostfour_1 |
issue_dns_hostfour_1 | Non-authoritative answer:
issue_dns_hostfour_1 |
issue_dns_hostfour_1 | *** Can't find hostone: No answer
issue_dns_hostfour_1 |
issue_dns_hostfour_1 | -----
...
```

As expected ```busybox:glibc``` does work:
```
...
issue_dns_hostfive_1 | Server:		127.0.0.11
issue_dns_hostfive_1 | Address:	127.0.0.11:53
issue_dns_hostfive_1 |
issue_dns_hostfive_1 | Non-authoritative answer:
issue_dns_hostfive_1 |
issue_dns_hostfive_1 | Non-authoritative answer:
issue_dns_hostfive_1 | Name:	hostone
issue_dns_hostfive_1 | Address: 192.168.0.4
issue_dns_hostfive_1 |
issue_dns_hostfive_1 | -----
...
```

Does anyone know if ```quay.io/prometheus/busybox:latest``` at some time switched from glibc to uclibc? Just to know where to search further (if uclibc ever worked e.g.) ...

**Comment by SuperQ** [comment]
That's a good question, we might need to roll back to 1.28 for now.

**Comment by johanneswuerbach** [comment]
This should be resolved now as the latest images are build based on busybox `1.30.0`.

**Comment by SuperQ** [comment]
Thanks for the update.

**Comment by m-kraus** [comment]
@SuperQ: Just for the record: 1.30 (uclibc) still acts weird when using nslookup:

1.28 uclibc

```
$ kubectl run --rm -ti --image=busybox:1.28 --restart=Never busybox -- nslookup prometheus.monitoring.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      prometheus.monitoring.svc.cluster.local
Address 1: 10.104.43.17 prometheus.monitoring.svc.cluster.local
```

1.30 uclibc

```
$kubectl run --rm -ti --image=busybox:1.30 --restart=Never busybox -- nslookup prometheus.monitoring.svc.cluster.local
If you don't see a command prompt, try pressing enter.

*** Can't find prometheus.monitoring.svc.cluster.local: No answer
```

1.30 glibc

```
$ kubectl run --rm -ti --image=busybox:1.30-glibc --restart=Never busybox -- nslookup prometheus.monitoring.svc.cluster.local
Server:		10.96.0.10
Address:	10.96.0.10:53

Name:	prometheus.monitoring.svc.cluster.local
Address: 10.104.43.17
```

The answer is also different compared to 1.28.

I still do not understand, if this is only related to the included nslookup. With prometheus-images based off this image, i do not notice any issues. But trying to get dns_sd to work in Thanos (based upon this image as well) and debugging it, i ran into the problems above again.

Not sure if we should reopen this issue. If you have suggestions for me to further debug this issues, please let me know.

Best regards, Michael

**Comment by SuperQ** [comment]
The upstream issue claims it's fixed since 2018-08-01.

**Comment by m-kraus** [comment]
Update: Prometheus and Thanos are seemingly not affected, since i got Thanos' dns_sd to work now (after fixing my own bugs...).
But while debugging with the help of https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/ i had to use busybox:1.28 explicitly, otherwise none of the commands returned something.

I suggest we keep this issue closed here, since "only" busybox' nslookup seems to have issues.
